<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <title> xxx </title>
    <link rel="stylesheet" href=" xxx  " />
  </head>
  <body>
     <nav> 
       <p>Ceci sera le menu !!!! test git </p>
       <a href="./index.php?action=accueil">Accueil</a>
       <a href="./index.php?action=chercher">Rechercher</a>
       <a href="./index.php?action=contact">Contact test</a>
      </nav>